//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectedClients
    {
        public int Id { get; set; }
        public int IdWorkers { get; set; }
        public int IdClients { get; set; }
        public int IdRates { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rates Rates { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
