//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceOrder
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdWorker { get; set; }
        public int IdInventory { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
